name: Run Tests E2E

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Installation of dependencies
      run: |
        npm install

    - name: Tests execution
      run: |
        npm run test:e2e
